### ISSUE TITLE
trace call in writeToArray

### ISSUE THREAD

**Issue by jtheuer** [xerial/larray#50]
Hi,

I use LArray as offheap storage. I use different access methods but one was surprisingly slow. I then notices this trace call:

https://github.com/xerial/larray/blob/16e661e7eab8608cc271d5a8c763820e327910e0/larray/src/main/scala/xerial/larray/LArray.scala#L714

Could it be a performance bottleneck? Did I misconfigure my internal logger? (I don't see that output, so it isn't actually logged) Is it maybe accidentally there, I didn't see trace calls in other methods? Is there an alternative method I can use to obtain a byte[], I want to implement ```copyBytes(long bytePos, byte[] target, int length)```?

**Comment by xerial** [comment]
OK. I'll replace it to a macro based one which is far more efficient, or remove it.

**Comment by jtheuer** [comment]
Cool, thanks. Any idea for a workaround in the mean time?

**Comment by xerial** [comment]
I've just released 0.3.4. Try this version

**Comment by jtheuer** [comment]
Excellent, that was quick!
Any chance to get the java dependency updated, too? (Or I probably just have to wait a bit until it appears...?)

**Comment by xerial** [comment]
Yes. Just need to wait a little bit until the new version will be synchronized to Maven Central.

**Comment by xerial** [comment]
Now it's available in Maven.
http://central.maven.org/maven2/org/xerial/larray/larray_2.11/
